server:
  image: nginx:stable-alpine
  ports:
    - "5173:80"
  build:
    context: ./client
    dockerfile: Dockerfile
  depends_on:
    - backend

backend:
  build:
    context: ./server
    dockerfile: Dockerfile
  env_file:
    - .env
  ports:
    - "3000:3000"
  depends_on:
    - db

db:
  image: postgres:15-alpine
  environment:
    POSTGRES_USER: autoreply
    POSTGRES_PASSWORD: autoreply_password
    POSTGRES_DB: autoreply
  volumes:
    - db-data:/var/lib/postgresql/data
  ports:
    - "5432:5432"

volumes:
  db-data:
